# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        Casting Club 
    #description:  
    #keywords:     
    #language:     es
    #robots:       index, follow

  stylesheets:    [ screen.css ]

  javascripts:    [ jquery-1.4.1.min.js,  ui.core.js ,  ui.checkbox.js, jquery.bind.js,  jquery.selectbox-0.5.js,  jquery.selectbox-0.5_style_2.js,  jquery.filestyle.js, custom_jquery.js, jquery.tooltip.js,  jquery.dimensions.js,  date.js, jquery.datePicker.js, personas.js, jquery.pngFix.pack.js ]

  has_layout:     true
  layout:         layout
