<?php


/**
 * Base class that represents a query for the 'casting' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Fri Mar  4 00:48:22 2011
 *
 * @method     CastingQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     CastingQuery orderByNombre($order = Criteria::ASC) Order by the nombre column
 * @method     CastingQuery orderByAnio($order = Criteria::ASC) Order by the anio column
 * @method     CastingQuery orderByFecha($order = Criteria::ASC) Order by the fecha column
 * @method     CastingQuery orderByEstado($order = Criteria::ASC) Order by the estado column
 * @method     CastingQuery orderByUpdatedAt($order = Criteria::ASC) Order by the updated_at column
 * @method     CastingQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 *
 * @method     CastingQuery groupById() Group by the id column
 * @method     CastingQuery groupByNombre() Group by the nombre column
 * @method     CastingQuery groupByAnio() Group by the anio column
 * @method     CastingQuery groupByFecha() Group by the fecha column
 * @method     CastingQuery groupByEstado() Group by the estado column
 * @method     CastingQuery groupByUpdatedAt() Group by the updated_at column
 * @method     CastingQuery groupByCreatedAt() Group by the created_at column
 *
 * @method     CastingQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     CastingQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     CastingQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     CastingQuery leftJoinPersonaCasting($relationAlias = null) Adds a LEFT JOIN clause to the query using the PersonaCasting relation
 * @method     CastingQuery rightJoinPersonaCasting($relationAlias = null) Adds a RIGHT JOIN clause to the query using the PersonaCasting relation
 * @method     CastingQuery innerJoinPersonaCasting($relationAlias = null) Adds a INNER JOIN clause to the query using the PersonaCasting relation
 *
 * @method     Casting findOne(PropelPDO $con = null) Return the first Casting matching the query
 * @method     Casting findOneOrCreate(PropelPDO $con = null) Return the first Casting matching the query, or a new Casting object populated from the query conditions when no match is found
 *
 * @method     Casting findOneById(int $id) Return the first Casting filtered by the id column
 * @method     Casting findOneByNombre(string $nombre) Return the first Casting filtered by the nombre column
 * @method     Casting findOneByAnio(string $anio) Return the first Casting filtered by the anio column
 * @method     Casting findOneByFecha(string $fecha) Return the first Casting filtered by the fecha column
 * @method     Casting findOneByEstado(int $estado) Return the first Casting filtered by the estado column
 * @method     Casting findOneByUpdatedAt(string $updated_at) Return the first Casting filtered by the updated_at column
 * @method     Casting findOneByCreatedAt(string $created_at) Return the first Casting filtered by the created_at column
 *
 * @method     array findById(int $id) Return Casting objects filtered by the id column
 * @method     array findByNombre(string $nombre) Return Casting objects filtered by the nombre column
 * @method     array findByAnio(string $anio) Return Casting objects filtered by the anio column
 * @method     array findByFecha(string $fecha) Return Casting objects filtered by the fecha column
 * @method     array findByEstado(int $estado) Return Casting objects filtered by the estado column
 * @method     array findByUpdatedAt(string $updated_at) Return Casting objects filtered by the updated_at column
 * @method     array findByCreatedAt(string $created_at) Return Casting objects filtered by the created_at column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseCastingQuery extends ModelCriteria
{

	/**
	 * Initializes internal state of BaseCastingQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'Casting', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new CastingQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    CastingQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof CastingQuery) {
			return $criteria;
		}
		$query = new CastingQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    Casting|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = CastingPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{	
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    CastingQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(CastingPeer::ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    CastingQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(CastingPeer::ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the id column
	 * 
	 * @param     int|array $id The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    CastingQuery The current query, for fluid interface
	 */
	public function filterById($id = null, $comparison = null)
	{
		if (is_array($id) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(CastingPeer::ID, $id, $comparison);
	}

	/**
	 * Filter the query on the nombre column
	 * 
	 * @param     string $nombre The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    CastingQuery The current query, for fluid interface
	 */
	public function filterByNombre($nombre = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($nombre)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $nombre)) {
				$nombre = str_replace('*', '%', $nombre);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(CastingPeer::NOMBRE, $nombre, $comparison);
	}

	/**
	 * Filter the query on the anio column
	 * 
	 * @param     string $anio The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    CastingQuery The current query, for fluid interface
	 */
	public function filterByAnio($anio = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($anio)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $anio)) {
				$anio = str_replace('*', '%', $anio);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(CastingPeer::ANIO, $anio, $comparison);
	}

	/**
	 * Filter the query on the fecha column
	 * 
	 * @param     string|array $fecha The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    CastingQuery The current query, for fluid interface
	 */
	public function filterByFecha($fecha = null, $comparison = null)
	{
		if (is_array($fecha)) {
			$useMinMax = false;
			if (isset($fecha['min'])) {
				$this->addUsingAlias(CastingPeer::FECHA, $fecha['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($fecha['max'])) {
				$this->addUsingAlias(CastingPeer::FECHA, $fecha['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(CastingPeer::FECHA, $fecha, $comparison);
	}

	/**
	 * Filter the query on the estado column
	 * 
	 * @param     int|array $estado The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    CastingQuery The current query, for fluid interface
	 */
	public function filterByEstado($estado = null, $comparison = null)
	{
		if (is_array($estado)) {
			$useMinMax = false;
			if (isset($estado['min'])) {
				$this->addUsingAlias(CastingPeer::ESTADO, $estado['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($estado['max'])) {
				$this->addUsingAlias(CastingPeer::ESTADO, $estado['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(CastingPeer::ESTADO, $estado, $comparison);
	}

	/**
	 * Filter the query on the updated_at column
	 * 
	 * @param     string|array $updatedAt The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    CastingQuery The current query, for fluid interface
	 */
	public function filterByUpdatedAt($updatedAt = null, $comparison = null)
	{
		if (is_array($updatedAt)) {
			$useMinMax = false;
			if (isset($updatedAt['min'])) {
				$this->addUsingAlias(CastingPeer::UPDATED_AT, $updatedAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($updatedAt['max'])) {
				$this->addUsingAlias(CastingPeer::UPDATED_AT, $updatedAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(CastingPeer::UPDATED_AT, $updatedAt, $comparison);
	}

	/**
	 * Filter the query on the created_at column
	 * 
	 * @param     string|array $createdAt The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    CastingQuery The current query, for fluid interface
	 */
	public function filterByCreatedAt($createdAt = null, $comparison = null)
	{
		if (is_array($createdAt)) {
			$useMinMax = false;
			if (isset($createdAt['min'])) {
				$this->addUsingAlias(CastingPeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($createdAt['max'])) {
				$this->addUsingAlias(CastingPeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(CastingPeer::CREATED_AT, $createdAt, $comparison);
	}

	/**
	 * Filter the query by a related PersonaCasting object
	 *
	 * @param     PersonaCasting $personaCasting  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    CastingQuery The current query, for fluid interface
	 */
	public function filterByPersonaCasting($personaCasting, $comparison = null)
	{
		return $this
			->addUsingAlias(CastingPeer::ID, $personaCasting->getCastingId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the PersonaCasting relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    CastingQuery The current query, for fluid interface
	 */
	public function joinPersonaCasting($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('PersonaCasting');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'PersonaCasting');
		}
		
		return $this;
	}

	/**
	 * Use the PersonaCasting relation PersonaCasting object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    PersonaCastingQuery A secondary query class using the current class as primary query
	 */
	public function usePersonaCastingQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
	{
		return $this
			->joinPersonaCasting($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'PersonaCasting', 'PersonaCastingQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     Casting $casting Object to remove from the list of results
	 *
	 * @return    CastingQuery The current query, for fluid interface
	 */
	public function prune($casting = null)
	{
		if ($casting) {
			$this->addUsingAlias(CastingPeer::ID, $casting->getId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

} // BaseCastingQuery
