<?php


/**
 * Base class that represents a query for the 'sinonimo_tabla' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Fri Mar  4 00:48:23 2011
 *
 * @method     SinonimoTablaQuery orderByTabla($order = Criteria::ASC) Order by the tabla column
 * @method     SinonimoTablaQuery orderById($order = Criteria::ASC) Order by the id column
 *
 * @method     SinonimoTablaQuery groupByTabla() Group by the tabla column
 * @method     SinonimoTablaQuery groupById() Group by the id column
 *
 * @method     SinonimoTablaQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     SinonimoTablaQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     SinonimoTablaQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     SinonimoTabla findOne(PropelPDO $con = null) Return the first SinonimoTabla matching the query
 * @method     SinonimoTabla findOneOrCreate(PropelPDO $con = null) Return the first SinonimoTabla matching the query, or a new SinonimoTabla object populated from the query conditions when no match is found
 *
 * @method     SinonimoTabla findOneByTabla(string $tabla) Return the first SinonimoTabla filtered by the tabla column
 * @method     SinonimoTabla findOneById(int $id) Return the first SinonimoTabla filtered by the id column
 *
 * @method     array findByTabla(string $tabla) Return SinonimoTabla objects filtered by the tabla column
 * @method     array findById(int $id) Return SinonimoTabla objects filtered by the id column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseSinonimoTablaQuery extends ModelCriteria
{

	/**
	 * Initializes internal state of BaseSinonimoTablaQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'SinonimoTabla', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new SinonimoTablaQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    SinonimoTablaQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof SinonimoTablaQuery) {
			return $criteria;
		}
		$query = new SinonimoTablaQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    SinonimoTabla|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = SinonimoTablaPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{	
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    SinonimoTablaQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(SinonimoTablaPeer::ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    SinonimoTablaQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(SinonimoTablaPeer::ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the tabla column
	 * 
	 * @param     string $tabla The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    SinonimoTablaQuery The current query, for fluid interface
	 */
	public function filterByTabla($tabla = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($tabla)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $tabla)) {
				$tabla = str_replace('*', '%', $tabla);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(SinonimoTablaPeer::TABLA, $tabla, $comparison);
	}

	/**
	 * Filter the query on the id column
	 * 
	 * @param     int|array $id The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    SinonimoTablaQuery The current query, for fluid interface
	 */
	public function filterById($id = null, $comparison = null)
	{
		if (is_array($id) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(SinonimoTablaPeer::ID, $id, $comparison);
	}

	/**
	 * Exclude object from result
	 *
	 * @param     SinonimoTabla $sinonimoTabla Object to remove from the list of results
	 *
	 * @return    SinonimoTablaQuery The current query, for fluid interface
	 */
	public function prune($sinonimoTabla = null)
	{
		if ($sinonimoTabla) {
			$this->addUsingAlias(SinonimoTablaPeer::ID, $sinonimoTabla->getId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

} // BaseSinonimoTablaQuery
