<?php



/**
 * This class defines the structure of the 'persona_casting' table.
 *
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Wed Mar  2 22:33:45 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class PersonaCastingTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PersonaCastingTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('persona_casting');
		$this->setPhpName('PersonaCasting');
		$this->setClassname('PersonaCasting');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addForeignKey('PERSONA_ID', 'PersonaId', 'INTEGER', 'persona', 'ID', false, null, null);
		$this->addForeignKey('CASTING_ID', 'CastingId', 'INTEGER', 'casting', 'ID', false, null, null);
		$this->addForeignKey('AGENCIA_ID', 'AgenciaId', 'INTEGER', 'agencia', 'ID', false, null, null);
		$this->addColumn('PESO', 'Peso', 'INTEGER', true, null, 0);
		$this->addColumn('ALTURA', 'Altura', 'INTEGER', true, null, 0);
		$this->addColumn('EMAIL', 'Email', 'VARCHAR', false, 45, null);
		$this->addColumn('TELEFONO', 'Telefono', 'VARCHAR', false, 20, null);
		$this->addColumn('CELULAR', 'Celular', 'VARCHAR', false, 20, null);
		$this->addColumn('CALZADO', 'Calzado', 'VARCHAR', false, 20, '-1');
		$this->addColumn('PANTALON', 'Pantalon', 'VARCHAR', false, 20, '-1');
		$this->addColumn('CAMISA', 'Camisa', 'VARCHAR', false, 20, '-1');
		$this->addColumn('OBSERVACIONES', 'Observaciones', 'LONGVARCHAR', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Persona', 'Persona', RelationMap::MANY_TO_ONE, array('persona_id' => 'id', ), null, null);
    $this->addRelation('Casting', 'Casting', RelationMap::MANY_TO_ONE, array('casting_id' => 'id', ), null, null);
    $this->addRelation('Agencia', 'Agencia', RelationMap::MANY_TO_ONE, array('agencia_id' => 'id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('update_column' => 'updated_at', 'create_column' => 'created_at', ),
		);
	} // getBehaviors()

} // PersonaCastingTableMap
