<?php


/**
 * Base static class for performing query and update operations on the 'cast_import' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Wed Mar  2 22:33:45 2011
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseCastImportPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'cast_import';

	/** the related Propel class for this table */
	const OM_CLASS = 'CastImport';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.CastImport';

	/** the related TableMap class for this table */
	const TM_CLASS = 'CastImportTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 21;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the CODIGO field */
	const CODIGO = 'cast_import.CODIGO';

	/** the column name for the NOMBRE field */
	const NOMBRE = 'cast_import.NOMBRE';

	/** the column name for the AGENCIA field */
	const AGENCIA = 'cast_import.AGENCIA';

	/** the column name for the PANTALON field */
	const PANTALON = 'cast_import.PANTALON';

	/** the column name for the CAMISA field */
	const CAMISA = 'cast_import.CAMISA';

	/** the column name for the CALZADO field */
	const CALZADO = 'cast_import.CALZADO';

	/** the column name for the ALTURA field */
	const ALTURA = 'cast_import.ALTURA';

	/** the column name for the PESO field */
	const PESO = 'cast_import.PESO';

	/** the column name for the FECHA_NACIMIENTO field */
	const FECHA_NACIMIENTO = 'cast_import.FECHA_NACIMIENTO';

	/** the column name for the FECHA_CASTING field */
	const FECHA_CASTING = 'cast_import.FECHA_CASTING';

	/** the column name for the CASTING field */
	const CASTING = 'cast_import.CASTING';

	/** the column name for the ANIO field */
	const ANIO = 'cast_import.ANIO';

	/** the column name for the MEDIDAS field */
	const MEDIDAS = 'cast_import.MEDIDAS';

	/** the column name for the DNI field */
	const DNI = 'cast_import.DNI';

	/** the column name for the OBSERVACIONES field */
	const OBSERVACIONES = 'cast_import.OBSERVACIONES';

	/** the column name for the TELEFONO field */
	const TELEFONO = 'cast_import.TELEFONO';

	/** the column name for the CELULAR field */
	const CELULAR = 'cast_import.CELULAR';

	/** the column name for the EMAIL field */
	const EMAIL = 'cast_import.EMAIL';

	/** the column name for the EDAD field */
	const EDAD = 'cast_import.EDAD';

	/** the column name for the DIA field */
	const DIA = 'cast_import.DIA';

	/** the column name for the ID field */
	const ID = 'cast_import.ID';

	/**
	 * An identiy map to hold any loaded instances of CastImport objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array CastImport[]
	 */
	public static $instances = array();


	// symfony behavior
	
	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Codigo', 'Nombre', 'Agencia', 'Pantalon', 'Camisa', 'Calzado', 'Altura', 'Peso', 'FechaNacimiento', 'FechaCasting', 'Casting', 'Anio', 'Medidas', 'Dni', 'Observaciones', 'Telefono', 'Celular', 'Email', 'Edad', 'Dia', 'Id', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('codigo', 'nombre', 'agencia', 'pantalon', 'camisa', 'calzado', 'altura', 'peso', 'fechaNacimiento', 'fechaCasting', 'casting', 'anio', 'medidas', 'dni', 'observaciones', 'telefono', 'celular', 'email', 'edad', 'dia', 'id', ),
		BasePeer::TYPE_COLNAME => array (self::CODIGO, self::NOMBRE, self::AGENCIA, self::PANTALON, self::CAMISA, self::CALZADO, self::ALTURA, self::PESO, self::FECHA_NACIMIENTO, self::FECHA_CASTING, self::CASTING, self::ANIO, self::MEDIDAS, self::DNI, self::OBSERVACIONES, self::TELEFONO, self::CELULAR, self::EMAIL, self::EDAD, self::DIA, self::ID, ),
		BasePeer::TYPE_RAW_COLNAME => array ('CODIGO', 'NOMBRE', 'AGENCIA', 'PANTALON', 'CAMISA', 'CALZADO', 'ALTURA', 'PESO', 'FECHA_NACIMIENTO', 'FECHA_CASTING', 'CASTING', 'ANIO', 'MEDIDAS', 'DNI', 'OBSERVACIONES', 'TELEFONO', 'CELULAR', 'EMAIL', 'EDAD', 'DIA', 'ID', ),
		BasePeer::TYPE_FIELDNAME => array ('codigo', 'nombre', 'agencia', 'pantalon', 'camisa', 'calzado', 'altura', 'peso', 'fecha_nacimiento', 'fecha_casting', 'casting', 'anio', 'medidas', 'dni', 'observaciones', 'telefono', 'celular', 'email', 'edad', 'dia', 'id', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Codigo' => 0, 'Nombre' => 1, 'Agencia' => 2, 'Pantalon' => 3, 'Camisa' => 4, 'Calzado' => 5, 'Altura' => 6, 'Peso' => 7, 'FechaNacimiento' => 8, 'FechaCasting' => 9, 'Casting' => 10, 'Anio' => 11, 'Medidas' => 12, 'Dni' => 13, 'Observaciones' => 14, 'Telefono' => 15, 'Celular' => 16, 'Email' => 17, 'Edad' => 18, 'Dia' => 19, 'Id' => 20, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('codigo' => 0, 'nombre' => 1, 'agencia' => 2, 'pantalon' => 3, 'camisa' => 4, 'calzado' => 5, 'altura' => 6, 'peso' => 7, 'fechaNacimiento' => 8, 'fechaCasting' => 9, 'casting' => 10, 'anio' => 11, 'medidas' => 12, 'dni' => 13, 'observaciones' => 14, 'telefono' => 15, 'celular' => 16, 'email' => 17, 'edad' => 18, 'dia' => 19, 'id' => 20, ),
		BasePeer::TYPE_COLNAME => array (self::CODIGO => 0, self::NOMBRE => 1, self::AGENCIA => 2, self::PANTALON => 3, self::CAMISA => 4, self::CALZADO => 5, self::ALTURA => 6, self::PESO => 7, self::FECHA_NACIMIENTO => 8, self::FECHA_CASTING => 9, self::CASTING => 10, self::ANIO => 11, self::MEDIDAS => 12, self::DNI => 13, self::OBSERVACIONES => 14, self::TELEFONO => 15, self::CELULAR => 16, self::EMAIL => 17, self::EDAD => 18, self::DIA => 19, self::ID => 20, ),
		BasePeer::TYPE_RAW_COLNAME => array ('CODIGO' => 0, 'NOMBRE' => 1, 'AGENCIA' => 2, 'PANTALON' => 3, 'CAMISA' => 4, 'CALZADO' => 5, 'ALTURA' => 6, 'PESO' => 7, 'FECHA_NACIMIENTO' => 8, 'FECHA_CASTING' => 9, 'CASTING' => 10, 'ANIO' => 11, 'MEDIDAS' => 12, 'DNI' => 13, 'OBSERVACIONES' => 14, 'TELEFONO' => 15, 'CELULAR' => 16, 'EMAIL' => 17, 'EDAD' => 18, 'DIA' => 19, 'ID' => 20, ),
		BasePeer::TYPE_FIELDNAME => array ('codigo' => 0, 'nombre' => 1, 'agencia' => 2, 'pantalon' => 3, 'camisa' => 4, 'calzado' => 5, 'altura' => 6, 'peso' => 7, 'fecha_nacimiento' => 8, 'fecha_casting' => 9, 'casting' => 10, 'anio' => 11, 'medidas' => 12, 'dni' => 13, 'observaciones' => 14, 'telefono' => 15, 'celular' => 16, 'email' => 17, 'edad' => 18, 'dia' => 19, 'id' => 20, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. CastImportPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(CastImportPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      Criteria $criteria object containing the columns to add.
	 * @param      string   $alias    optional table alias
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria, $alias = null)
	{
		if (null === $alias) {
			$criteria->addSelectColumn(CastImportPeer::CODIGO);
			$criteria->addSelectColumn(CastImportPeer::NOMBRE);
			$criteria->addSelectColumn(CastImportPeer::AGENCIA);
			$criteria->addSelectColumn(CastImportPeer::PANTALON);
			$criteria->addSelectColumn(CastImportPeer::CAMISA);
			$criteria->addSelectColumn(CastImportPeer::CALZADO);
			$criteria->addSelectColumn(CastImportPeer::ALTURA);
			$criteria->addSelectColumn(CastImportPeer::PESO);
			$criteria->addSelectColumn(CastImportPeer::FECHA_NACIMIENTO);
			$criteria->addSelectColumn(CastImportPeer::FECHA_CASTING);
			$criteria->addSelectColumn(CastImportPeer::CASTING);
			$criteria->addSelectColumn(CastImportPeer::ANIO);
			$criteria->addSelectColumn(CastImportPeer::MEDIDAS);
			$criteria->addSelectColumn(CastImportPeer::DNI);
			$criteria->addSelectColumn(CastImportPeer::OBSERVACIONES);
			$criteria->addSelectColumn(CastImportPeer::TELEFONO);
			$criteria->addSelectColumn(CastImportPeer::CELULAR);
			$criteria->addSelectColumn(CastImportPeer::EMAIL);
			$criteria->addSelectColumn(CastImportPeer::EDAD);
			$criteria->addSelectColumn(CastImportPeer::DIA);
			$criteria->addSelectColumn(CastImportPeer::ID);
		} else {
			$criteria->addSelectColumn($alias . '.CODIGO');
			$criteria->addSelectColumn($alias . '.NOMBRE');
			$criteria->addSelectColumn($alias . '.AGENCIA');
			$criteria->addSelectColumn($alias . '.PANTALON');
			$criteria->addSelectColumn($alias . '.CAMISA');
			$criteria->addSelectColumn($alias . '.CALZADO');
			$criteria->addSelectColumn($alias . '.ALTURA');
			$criteria->addSelectColumn($alias . '.PESO');
			$criteria->addSelectColumn($alias . '.FECHA_NACIMIENTO');
			$criteria->addSelectColumn($alias . '.FECHA_CASTING');
			$criteria->addSelectColumn($alias . '.CASTING');
			$criteria->addSelectColumn($alias . '.ANIO');
			$criteria->addSelectColumn($alias . '.MEDIDAS');
			$criteria->addSelectColumn($alias . '.DNI');
			$criteria->addSelectColumn($alias . '.OBSERVACIONES');
			$criteria->addSelectColumn($alias . '.TELEFONO');
			$criteria->addSelectColumn($alias . '.CELULAR');
			$criteria->addSelectColumn($alias . '.EMAIL');
			$criteria->addSelectColumn($alias . '.EDAD');
			$criteria->addSelectColumn($alias . '.DIA');
			$criteria->addSelectColumn($alias . '.ID');
		}
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(CastImportPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CastImportPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(CastImportPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseCastImportPeer', $criteria, $con);
		}

		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     CastImport
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = CastImportPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return CastImportPeer::populateObjects(CastImportPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(CastImportPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			CastImportPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BaseCastImportPeer', $criteria, $con);
		}


		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      CastImport $value A CastImport object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(CastImport $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A CastImport object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof CastImport) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or CastImport object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     CastImport Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to cast_import
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 20] === null) {
			return null;
		}
		return (string) $row[$startcol + 20];
	}

	/**
	 * Retrieves the primary key from the DB resultset row 
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, an array of the primary key columns will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     mixed The primary key of the row
	 */
	public static function getPrimaryKeyFromRow($row, $startcol = 0)
	{
		return (int) $row[$startcol + 20];
	}
	
	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = CastImportPeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = CastImportPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = CastImportPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://www.propelorm.org/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				CastImportPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}
	/**
	 * Populates an object of the default type or an object that inherit from the default.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     array (CastImport object, last column rank)
	 */
	public static function populateObject($row, $startcol = 0)
	{
		$key = CastImportPeer::getPrimaryKeyHashFromRow($row, $startcol);
		if (null !== ($obj = CastImportPeer::getInstanceFromPool($key))) {
			// We no longer rehydrate the object, since this can cause data loss.
			// See http://www.propelorm.org/ticket/509
			// $obj->hydrate($row, $startcol, true); // rehydrate
			$col = $startcol + CastImportPeer::NUM_COLUMNS;
		} else {
			$cls = CastImportPeer::OM_CLASS;
			$obj = new $cls();
			$col = $obj->hydrate($row, $startcol);
			CastImportPeer::addInstanceToPool($obj, $key);
		}
		return array($obj, $col);
	}
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(BaseCastImportPeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(BaseCastImportPeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new CastImportTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean $withPrefix Whether or not to return the path with the class name
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? CastImportPeer::CLASS_DEFAULT : CastImportPeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a CastImport or Criteria object.
	 *
	 * @param      mixed $values Criteria or CastImport object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(CastImportPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from CastImport object
		}

		if ($criteria->containsKey(CastImportPeer::ID) && $criteria->keyContainsValue(CastImportPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.CastImportPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a CastImport or Criteria object.
	 *
	 * @param      mixed $values Criteria or CastImport object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(CastImportPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(CastImportPeer::ID);
			$value = $criteria->remove(CastImportPeer::ID);
			if ($value) {
				$selectCriteria->add(CastImportPeer::ID, $value, $comparison);
			} else {
				$selectCriteria->setPrimaryTableName(CastImportPeer::TABLE_NAME);
			}

		} else { // $values is CastImport object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		return BasePeer::doUpdate($selectCriteria, $criteria, $con);
	}

	/**
	 * Method to DELETE all rows from the cast_import table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(CastImportPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(CastImportPeer::TABLE_NAME, $con, CastImportPeer::DATABASE_NAME);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			CastImportPeer::clearInstancePool();
			CastImportPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a CastImport or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or CastImport object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(CastImportPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			CastImportPeer::clearInstancePool();
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof CastImport) { // it's a model object
			// invalidate the cache for this single object
			CastImportPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(CastImportPeer::ID, (array) $values, Criteria::IN);
			// invalidate the cache for this object(s)
			foreach ((array) $values as $singleval) {
				CastImportPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			CastImportPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given CastImport object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      CastImport $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(CastImport $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(CastImportPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(CastImportPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(CastImportPeer::DATABASE_NAME, CastImportPeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     CastImport
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = CastImportPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(CastImportPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(CastImportPeer::DATABASE_NAME);
		$criteria->add(CastImportPeer::ID, $pk);

		$v = CastImportPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(CastImportPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(CastImportPeer::DATABASE_NAME);
			$criteria->add(CastImportPeer::ID, $pks, Criteria::IN);
			$objs = CastImportPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// symfony behavior
	
	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
	  return array();
	}

	// symfony_behaviors behavior
	
	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
	  if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
	  {
	    return sprintf('BaseCastImportPeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
	  }
	
	  throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}

} // BaseCastImportPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BaseCastImportPeer::buildTableMap();

