<?php


/**
 * Skeleton subclass for performing query and update operations on the 'agencia' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 01/22/11 21:25:06
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AgenciaPeer extends BaseAgenciaPeer {

	
	public static function buscar ( $nombre )
	{
		$agencia = null;
		
		if ( $nombre == "" )
		{
			$agencia = self::retrieveByPK(-1);
		}
		else
		{
			$c = new Criteria();
			
			$c->add ( self::NOMBRE , $nombre , Criteria::EQUAL );
			
			$agencias = self::doSelect($c);

			if ( count ( $agencias ) == 0 )
			{
				$agencia = new Agencia();
				$agencia->setNombre ( $nombre );
				$agencia->save();
			}
			else
			{
				$agencia = $agencias[0];
			}
		}
		return $agencia;
	}
	
} // AgenciaPeer
