<?php


/**
 * Skeleton subclass for performing query and update operations on the 'casting' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 01/22/11 21:25:06
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CastingPeer extends BaseCastingPeer {

	public static function buscar ( $nombre , $anio )
	{
		$casting = null;
		
		if ( $nombre == "" )
		{
			$casting = self::retrieveByPK(-1);
		}
		else
		{
			$c = new Criteria();
			
			$c->add ( self::NOMBRE , $nombre , Criteria::EQUAL );
			$c->add ( self::ANIO , $anio , Criteria::EQUAL );
			
			$castings = self::doSelect( $c );
			
			if ( count ( $castings ) == 0 )
			{
				$casting = new Casting();
				$casting->setNombre ( $nombre );
				$casting->setAnio ( $anio );
				$casting->save();
			}
			else
			{
				$casting = $castings[0];
			}
		}
		
		return $casting;
	}
	
} // CastingPeer
