/*
-- Query: SELECT * FROM `webapp`.`sinonimos`
LIMIT 0, 1000

-- Date: 2011-01-22 19:32
*/
INSERT INTO `sinonimos` (origen,destino) VALUES ('ALLTURA','HEIGHT');
INSERT INTO `sinonimos` (origen,destino) VALUES ('ALT','HEIGHT');
INSERT INTO `sinonimos` (origen,destino) VALUES ('ALT.','HEIGHT');
INSERT INTO `sinonimos` (origen,destino) VALUES ('ALTURA','HEIGHT');
INSERT INTO `sinonimos` (origen,destino) VALUES ('CEL','CELPHONE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('CELU','CELPHONE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('CELULAR','CELPHONE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('CODIGO','CODE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('CóDIGO','CODE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('DIA DE SCOUT','DATE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('DICIPLINA','ACTIVITIES');
INSERT INTO `sinonimos` (origen,destino) VALUES ('DISCIPLINAS, DEPORTES','ACTIVITIES');
INSERT INTO `sinonimos` (origen,destino) VALUES ('DISCIPLINAS, DEPORTES, ETC.','ACTIVITIES');
INSERT INTO `sinonimos` (origen,destino) VALUES ('DISCIPLINAS, DEPORTES, INSTRUMENTOS','ACTIVITIES');
INSERT INTO `sinonimos` (origen,destino) VALUES ('DISCIPLINAS, DEPORTES, INSTRUMENTOS, ETC.','ACTIVITIES');
INSERT INTO `sinonimos` (origen,destino) VALUES ('E MAIL','EMAIL');
INSERT INTO `sinonimos` (origen,destino) VALUES ('E-MAIL','EMAIL');
INSERT INTO `sinonimos` (origen,destino) VALUES ('EDAD','AGE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('EMAIL','EMAIL');
INSERT INTO `sinonimos` (origen,destino) VALUES ('FECHA','DATE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('FECHA DE NAC','BORNDATE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('FECHA DE NAC.','BORNDATE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('FECHA DE NACIMIENTO','BORNDATE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('FECHA DE SCOUT','DATE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('FECHA DE SCOUTING','DATE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('FECHA NAC','BORNDATE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('FECHA NAC.','BORNDATE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('FECHA SCOUT','DATE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('FECHA SCOUTING','DATE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('FECHS DE SCOUT','DATE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('IDIOMAS','LANGUAGES');
INSERT INTO `sinonimos` (origen,destino) VALUES ('LUBAR DE SCOUT','PLACE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('LUGAR DE SCOUT','PLACE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('LUGAR DE SCOUTING','PLACE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('LUGAR SCOUR','PLACE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('LUGAR SCOUT','PLACE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('LUGAR SCOUT.','PLACE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('LUGAR SCOUTING','PLACE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('MAIL','EMAIL');
INSERT INTO `sinonimos` (origen,destino) VALUES ('MOVI','CELPHONE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('MOVIL','CELPHONE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('MOVIL.','CELPHONE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('NACIONALIDAD','NACIONALITY');
INSERT INTO `sinonimos` (origen,destino) VALUES ('NOMBRE','NAME');
INSERT INTO `sinonimos` (origen,destino) VALUES ('NOMBRE Y APELLIDO','NAME');
INSERT INTO `sinonimos` (origen,destino) VALUES ('NOMBRE Y APRELLIDO','NAME');
INSERT INTO `sinonimos` (origen,destino) VALUES ('NRO','CODE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('Nª','CODE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('Nº','CODE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('NúMERO','CODE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('OBS','OBSERVATIONS');
INSERT INTO `sinonimos` (origen,destino) VALUES ('OBS.','OBSERVATIONS');
INSERT INTO `sinonimos` (origen,destino) VALUES ('OBSERVACIONES','OBSERVATIONS');
INSERT INTO `sinonimos` (origen,destino) VALUES ('OBSERVACIóN','OBSERVATIONS');
INSERT INTO `sinonimos` (origen,destino) VALUES ('PESO','WEIGHT');
INSERT INTO `sinonimos` (origen,destino) VALUES ('PESO.','WEIGHT');
INSERT INTO `sinonimos` (origen,destino) VALUES ('TEL','TELEPHONE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('TEL.','TELEPHONE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('TELEFONO','TELEPHONE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('TELéFONO','TELEPHONE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('N*','CODE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('N','CODE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('NO','CODE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('N°','CODE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('DNI','DOCUMENT');
INSERT INTO `sinonimos` (origen,destino) VALUES ('DNI','DOCUMENT');
INSERT INTO `sinonimos` (origen,destino) VALUES ('CALZADO','SHOE_SIZE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('AGENCIA','AGENCY');
INSERT INTO `sinonimos` (origen,destino) VALUES ('PANTALON','PANTS_SIZE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('CAMISA','SHIRT_SIZE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('FECHA DE NAC,','BORNDATE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('TELEFONOS','TELEPHONE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('FEC. DE NAC.','BORNDATE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('CAM','SHIRT_SIZE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('CAM.','SHIRT_SIZE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('PANT','PANTS_SIZE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('PANT.','PANTS_SIZE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('CALZ','SHOE_SIZE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('OBSEVACIONES','OBSERVATIONS');
INSERT INTO `sinonimos` (origen,destino) VALUES ('CALZ.','SHOE_SIZE');
INSERT INTO `sinonimos` (origen,destino) VALUES ('MEDIDAS','SIZES');
