<?php


/**
 * Base class that represents a query for the 'grupo_usuario' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Wed Mar  2 22:33:45 2011
 *
 * @method     GrupoUsuarioQuery orderByGrupoId($order = Criteria::ASC) Order by the grupo_id column
 * @method     GrupoUsuarioQuery orderByUsuarioId($order = Criteria::ASC) Order by the usuario_id column
 * @method     GrupoUsuarioQuery orderById($order = Criteria::ASC) Order by the id column
 *
 * @method     GrupoUsuarioQuery groupByGrupoId() Group by the grupo_id column
 * @method     GrupoUsuarioQuery groupByUsuarioId() Group by the usuario_id column
 * @method     GrupoUsuarioQuery groupById() Group by the id column
 *
 * @method     GrupoUsuarioQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     GrupoUsuarioQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     GrupoUsuarioQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     GrupoUsuarioQuery leftJoinGrupo($relationAlias = null) Adds a LEFT JOIN clause to the query using the Grupo relation
 * @method     GrupoUsuarioQuery rightJoinGrupo($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Grupo relation
 * @method     GrupoUsuarioQuery innerJoinGrupo($relationAlias = null) Adds a INNER JOIN clause to the query using the Grupo relation
 *
 * @method     GrupoUsuarioQuery leftJoinUsuario($relationAlias = null) Adds a LEFT JOIN clause to the query using the Usuario relation
 * @method     GrupoUsuarioQuery rightJoinUsuario($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Usuario relation
 * @method     GrupoUsuarioQuery innerJoinUsuario($relationAlias = null) Adds a INNER JOIN clause to the query using the Usuario relation
 *
 * @method     GrupoUsuario findOne(PropelPDO $con = null) Return the first GrupoUsuario matching the query
 * @method     GrupoUsuario findOneOrCreate(PropelPDO $con = null) Return the first GrupoUsuario matching the query, or a new GrupoUsuario object populated from the query conditions when no match is found
 *
 * @method     GrupoUsuario findOneByGrupoId(int $grupo_id) Return the first GrupoUsuario filtered by the grupo_id column
 * @method     GrupoUsuario findOneByUsuarioId(int $usuario_id) Return the first GrupoUsuario filtered by the usuario_id column
 * @method     GrupoUsuario findOneById(int $id) Return the first GrupoUsuario filtered by the id column
 *
 * @method     array findByGrupoId(int $grupo_id) Return GrupoUsuario objects filtered by the grupo_id column
 * @method     array findByUsuarioId(int $usuario_id) Return GrupoUsuario objects filtered by the usuario_id column
 * @method     array findById(int $id) Return GrupoUsuario objects filtered by the id column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseGrupoUsuarioQuery extends ModelCriteria
{

	/**
	 * Initializes internal state of BaseGrupoUsuarioQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'GrupoUsuario', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new GrupoUsuarioQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    GrupoUsuarioQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof GrupoUsuarioQuery) {
			return $criteria;
		}
		$query = new GrupoUsuarioQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    GrupoUsuario|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = GrupoUsuarioPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{	
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    GrupoUsuarioQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(GrupoUsuarioPeer::ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    GrupoUsuarioQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(GrupoUsuarioPeer::ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the grupo_id column
	 * 
	 * @param     int|array $grupoId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    GrupoUsuarioQuery The current query, for fluid interface
	 */
	public function filterByGrupoId($grupoId = null, $comparison = null)
	{
		if (is_array($grupoId)) {
			$useMinMax = false;
			if (isset($grupoId['min'])) {
				$this->addUsingAlias(GrupoUsuarioPeer::GRUPO_ID, $grupoId['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($grupoId['max'])) {
				$this->addUsingAlias(GrupoUsuarioPeer::GRUPO_ID, $grupoId['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(GrupoUsuarioPeer::GRUPO_ID, $grupoId, $comparison);
	}

	/**
	 * Filter the query on the usuario_id column
	 * 
	 * @param     int|array $usuarioId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    GrupoUsuarioQuery The current query, for fluid interface
	 */
	public function filterByUsuarioId($usuarioId = null, $comparison = null)
	{
		if (is_array($usuarioId)) {
			$useMinMax = false;
			if (isset($usuarioId['min'])) {
				$this->addUsingAlias(GrupoUsuarioPeer::USUARIO_ID, $usuarioId['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($usuarioId['max'])) {
				$this->addUsingAlias(GrupoUsuarioPeer::USUARIO_ID, $usuarioId['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(GrupoUsuarioPeer::USUARIO_ID, $usuarioId, $comparison);
	}

	/**
	 * Filter the query on the id column
	 * 
	 * @param     int|array $id The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    GrupoUsuarioQuery The current query, for fluid interface
	 */
	public function filterById($id = null, $comparison = null)
	{
		if (is_array($id) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(GrupoUsuarioPeer::ID, $id, $comparison);
	}

	/**
	 * Filter the query by a related Grupo object
	 *
	 * @param     Grupo $grupo  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    GrupoUsuarioQuery The current query, for fluid interface
	 */
	public function filterByGrupo($grupo, $comparison = null)
	{
		return $this
			->addUsingAlias(GrupoUsuarioPeer::GRUPO_ID, $grupo->getId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the Grupo relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    GrupoUsuarioQuery The current query, for fluid interface
	 */
	public function joinGrupo($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('Grupo');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'Grupo');
		}
		
		return $this;
	}

	/**
	 * Use the Grupo relation Grupo object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    GrupoQuery A secondary query class using the current class as primary query
	 */
	public function useGrupoQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
	{
		return $this
			->joinGrupo($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'Grupo', 'GrupoQuery');
	}

	/**
	 * Filter the query by a related Usuario object
	 *
	 * @param     Usuario $usuario  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    GrupoUsuarioQuery The current query, for fluid interface
	 */
	public function filterByUsuario($usuario, $comparison = null)
	{
		return $this
			->addUsingAlias(GrupoUsuarioPeer::USUARIO_ID, $usuario->getId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the Usuario relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    GrupoUsuarioQuery The current query, for fluid interface
	 */
	public function joinUsuario($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('Usuario');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'Usuario');
		}
		
		return $this;
	}

	/**
	 * Use the Usuario relation Usuario object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    UsuarioQuery A secondary query class using the current class as primary query
	 */
	public function useUsuarioQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
	{
		return $this
			->joinUsuario($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'Usuario', 'UsuarioQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     GrupoUsuario $grupoUsuario Object to remove from the list of results
	 *
	 * @return    GrupoUsuarioQuery The current query, for fluid interface
	 */
	public function prune($grupoUsuario = null)
	{
		if ($grupoUsuario) {
			$this->addUsingAlias(GrupoUsuarioPeer::ID, $grupoUsuario->getId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

} // BaseGrupoUsuarioQuery
