<?php



/**
 * This class defines the structure of the 'cast_import' table.
 *
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Fri Mar  4 00:48:23 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class CastImportTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.CastImportTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('cast_import');
		$this->setPhpName('CastImport');
		$this->setClassname('CastImport');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addColumn('CODIGO', 'Codigo', 'INTEGER', false, null, null);
		$this->addColumn('NOMBRE', 'Nombre', 'VARCHAR', false, 100, null);
		$this->addColumn('AGENCIA', 'Agencia', 'VARCHAR', false, 45, null);
		$this->addColumn('PANTALON', 'Pantalon', 'VARCHAR', false, 45, null);
		$this->addColumn('CAMISA', 'Camisa', 'VARCHAR', false, 45, null);
		$this->addColumn('CALZADO', 'Calzado', 'INTEGER', false, null, null);
		$this->addColumn('ALTURA', 'Altura', 'INTEGER', false, null, null);
		$this->addColumn('PESO', 'Peso', 'INTEGER', false, null, null);
		$this->addColumn('FECHA_NACIMIENTO', 'FechaNacimiento', 'VARCHAR', false, 45, null);
		$this->addColumn('FECHA_CASTING', 'FechaCasting', 'VARCHAR', false, 45, null);
		$this->addColumn('CASTING', 'Casting', 'VARCHAR', false, 45, null);
		$this->addColumn('ANIO', 'Anio', 'INTEGER', false, null, null);
		$this->addColumn('MEDIDAS', 'Medidas', 'VARCHAR', false, 45, null);
		$this->addColumn('DNI', 'Dni', 'VARCHAR', false, 45, null);
		$this->addColumn('OBSERVACIONES', 'Observaciones', 'LONGVARCHAR', false, null, null);
		$this->addColumn('TELEFONO', 'Telefono', 'VARCHAR', false, 45, null);
		$this->addColumn('CELULAR', 'Celular', 'VARCHAR', false, 45, null);
		$this->addColumn('EMAIL', 'Email', 'VARCHAR', false, 45, null);
		$this->addColumn('EDAD', 'Edad', 'INTEGER', false, null, null);
		$this->addColumn('DIA', 'Dia', 'VARCHAR', false, 45, null);
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // CastImportTableMap
