#ifndef H_COLUMNS_DEFS
#define H_COLUMNS_DEFS


#define COLUMN_CODE			"CODE"
#define COLUMN_DATE			"DATE"
#define COLUMN_NAME			"NAME"
#define COLUMN_BORNDATE		"BORNDATE"
#define COLUMN_AGE			"AGE"
#define COLUMN_TELEPHONE	"TELEPHONE"
#define COLUMN_CELPHONE		"CELPHONE"
#define COLUMN_HEIGHT		"HEIGHT"
#define COLUMN_WEIGHT		"WEIGHT"
#define COLUMN_OBSERVATIONS	"OBSERVATIONS"
#define COLUMN_PLACE		"PLACE"
#define COLUMN_EMAIL        "EMAIL"
#define COLUMN_ACTIVITIES   "ACTIVITIES"
#define COLUMN_NACIONALITY  "NACIONALITY"
#define COLUMN_LANGUAGES    "LANGUAGES"


#endif
