# config/schema.yml
# esquema de la base de datos para autogenerar classes
#
# @author Eric 
# @orm Propel
# @version 2.0

propel:
  nacionalidad:
    id: ~
    descripcion:  { type: varchar(100) , required. true, default: "" }
  agencia:
    id:           ~
    nombre:       { type: varchar(45), required: true, default: "" }
    prioridad:    { type: tinyint, required: true, default: 0 }
    persona_id:   ~
    updated_at:   ~
    created_at:   ~
  casting:
    id:           ~
    nombre:       { type: varchar(45), required: true, default: "" }
    anio:         { type: varchar(45), required: true, default: "" }
    fecha:        { type: date }
    estado:       { type: tinyint, default: -1 }
    proyecto_id:  ~
    updated_at:   ~
    created_at:   ~
  codigos_scouting:
    id:           ~
    codigo:       { type: varchar(2), required: true }
    descripcion:  { type: varchar(45), required: true, default: "" }
    updated_at:   ~
    created_at:   ~
  media:
    id:           ~
    archivo:      { type: varchar(45), required: true, default: "" }
    tipo:         { type: varchar(45), required: true, default: "" }
    persona_id:   ~
    personas_scouting_id:  { type: integer , default: -1 } 
    personas_casting_id:   { type: integer, default: -1  }
    orden:        { type: integer, required: true, default: 0 }
    created_at:   ~
  persona_casting:
    persona_id:     ~
    casting_id:     ~
    dia_casting_id: ~
    agencia_id:     ~
    peso:           { type: integer, required: true, default: 0 }
    altura:         { type: integer, required: true, default: 0 }
    email:          { type: varchar(45) }
    telefono:       { type: varchar(20) }
    celular:        { type: varchar(20) }
    calzado:        { type: varchar(20), default: -1 }
    pantalon:       { type: varchar(20), default: -1 }
    camisa:         { type: varchar(20), default: -1 }
    observaciones:  { type: longvarchar }
    orden:          { type: int }
    updated_at:   ~
    created_at:   ~
  persona:
    id:           ~
    nombre:       { type: varchar(100), required: true, default: "" }
    dni:          { type: varchar(20), required: true, default: 0 }
    fecha_nacimiento: { type: date, required: true, default: "0000-00-00" }
    sexo:         { type: varchar(1), required: true, default: "X" }
    peso:         { type: integer, required: true, default: 0 }
    altura:       { type: integer, required: true, default: 0 }
    email:        { type: varchar(45) }
    telefono:     { type: varchar(20) }
    celular:      { type: varchar(20) }
    calzado:      { type: varchar(20), default: -1 }
    pantalon:     { type: varchar(20), default: -1 }
    camisa:         { type: varchar(20), default: -1 }
    observaciones:  { type: longvarchar }  
    activo:         { type: int }
    fecha_actualizacion: { type: date, required: true, default: "0000-00-00" }
    nacionalidad_id:  ~
    created_at:   ~
  scout_import:
    id:           ~
    codigo:       { type: integer, required: true, default: 0 }
    edad:         { type: integer, default: null }
    peso:         { type: integer, default: null }
    altura:       { type: integer, default: null }
    nombre:       { type: varchar(100), default: null }
    fecha_nacimiento: { type: varchar(12), default: null }
    fecha_scout:  { type: varchar(12), default: null }
    lugar_scout:  { type: varchar(45), default: null }
    observaciones: { type: varchar(255), default: null }
    actividades:  { type: varchar(255), default: null }
    email:        { type: varchar(100), default: null }
    telefono:     { type: varchar(45), default: null }
    celular:      { type: varchar(45), default: null }
    nacionalidad:  { type: varchar(45), default: null }
    idiomas:      { type: varchar(255), default: null }
    xls_file:     { type: varchar(255), required: true, default: "" }
    anio:         { type: integer, required: true, default: 0 }
    mes:          { type: varchar(20), required: true, default: "" }
    codigo_agrupador: { type: varchar(45), required: true, default: "" }
    dia:          { type: varchar(45) , required: true, default: "" }
  persona_scouting: 
    id:           ~
    anio:         { type: integer, required: true, default: 0 }
    id_codigo:    { type: integer, required: true, default: 0 }
    mes:          { type: integer, required: true, default: 0 }
    dia_contador: { type: integer, required: true, default: 0 }
    fecha:        { type: date, default: null }
    persona_id:   ~
    peso:         { type: integer, required: true, default: 0 }
    altura:       { type: integer, required: true, default: 0 }
    email:        { type: varchar(45) }
    telefono:     { type: varchar(20) }
    celular:      { type: varchar(20) }
    actividades:  { type: varchar(255) }
    observaciones: { type: varchar(255), required: true, default: "" }
    lugar_id:      ~
    nacionalidad_id: ~
    created_at:   ~
    updated_at:   ~
  cast_import:
    codigo: { type: integer }
    nombre: { type: varchar(100) }
    agencia: { type: varchar(45) }
    pantalon: { type: varchar(45) }
    camisa: { type: varchar(45) }    
    calzado: { type: integer }
    altura: { type: integer }
    peso: { type: integer }
    fecha_nacimiento: { type: varchar(45) }
    fecha_casting: { type: varchar(45) }
    casting: { type: varchar(45) }
    anio: { type: integer  }
    medidas: { type: varchar(45) }
    dni: { type: varchar(45) }
    observaciones: { type: longvarchar }
    telefono: { type: varchar(45) }
    celular: { type: varchar(45) }
    email: { type: varchar(45) }
    edad: { type: integer }
    dia: { type: varchar(45) }
  sinonimo_tabla:
    tabla: { type: varchar(45) }
  sinonimo:
    origen:       { type: varchar(50), required: true, default: "" }
    destino:      { type: varchar(55), required: true, default: "" }
  lugar:
    id: ~
    descripcion:  { type: varchar(100) , required. true, default: "" }
    latitud:      { type: float, required: false, default: 0 }
    longitud:     { type: float, required: false, default: 0 }
  lenguaje:
    id: ~
    descripcion:  { type: varchar(100) , required. true, default: "" }
  persona_lenguaje:
    persona_id:   ~
    lenguaje_id:  ~
  label:
    id: ~
    descripcion:  { type: varchar(100) , required. true, default: "" }
  persona_label:
    persona_id:   ~
    label_id:     ~
  cliente:
    id: ~
    descripcion: { type: varchar(45), required: true }
    created_at: ~
    updated_at: ~
  agencia_publicidad:
    id: ~
    descripcion: { type: varchar(45), required: true }
    created_at: ~
    updated_at: ~
  productora:
    id: ~
    descripcion: { type: varchar(45), required: true }
    created_at: ~
    updated_at: ~
  castingera:
    id: ~
    descripcion: { type: varchar(45), required: true }
    created_at: ~
    updated_at: ~
  proyecto:
    id: ~
    descripcion: { type: varchar(45), required: true }
    cliente_id: ~
    agencia_publicidad_id: ~
    productora_id: ~
    castingera_id: ~
    guion: { type: varchar(45), required: true }
    brief: { type: varchar(45), required: true }
    precontrato: { type: varchar(45), required: true }
    timing_produccion: { type: varchar(45), required: true }
    timing_scouting: { type: varchar(45), required: true }
    presupuesto: { type: varchar(45) }
    usuario_director_id: { type: int}
    usuario_productor_id: { type: int }
    estado_id: ~
    created_at: ~
    updated_at: ~
  estado:
    id: ~
    descripcion: { type: varchar(45), required: true }
    created_at: ~
    updated_at: ~
  personaje:
    id: ~
    descripcion: { type: varchar(45), required: true }
    proyecto_id: ~
    cantidad: { type: int }
    created_at: ~
    updated_at: ~
  personaje_referencia:
    id: ~
    descripcion: { type: varchar(45), required: true }
    personaje_id: ~
    path_foto: { type: varchar(45), required: true }
    created_at: ~
    updated_at: ~
  dia_casting:
    id: ~
    descripcion: { type: varchar(45), required: true }
    fecha: { type: datetime , required:true }
    casting_id: ~
    created_at: ~
    updated_at: ~
  dia_casting_personaje:
    id: ~
    dia_casting_id: ~
    personaje_id: ~
    cantidad_ideal: { type: int }
    created_at: ~
    updated_at: ~
  dia_scouting:
    id: ~
    descripcion: { type: varchar(45), required: true }
    fecha: { type: datetime , required:true }
    proyecto_id: ~
    created_at: ~
    updated_at: ~
  persona_citacion_trace:
    id: ~
    persona_citacion_id: ~
    persona_id: ~
    created_at: ~
    updated_at: ~
  persona_citacion:
    id: ~
    persona_id: ~
    dia_casting_id: ~
    personaje_id: ~
    prioridad: { type: int }
    generico: { type: int }
    estado_id: ~
    franja_horaria_id: ~
    created_at: ~
    updated_at: ~
  franja_horaria:
    id: ~
    descripcion: { type: varchar(45) }
    created_at: ~
    updated_at: ~
  persona_seleccion:
    id: ~
    persona_id: ~
    personaje_id: ~
    estado: { type: int }
    created_at: ~
    updated_at: ~
  callback:
    id: ~
    descripcion: { type: varchar(45), required: true }
    fecha: { type: datetime , required:true }
    casting_id: ~
    created_at: ~
    updated_at: ~
  persona_callback:
    id: ~
    persona_seleccion_id: ~
    callback_id: ~
    created_at: ~
    updated_at: ~
