<?php


/**
 * Skeleton subclass for representing a row from the 'cast_import' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 01/22/11 21:25:08
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CastImport extends BaseCastImport {

	public function crearPersona ()
	{
		$ci = $this;
		
		// 1 - Busco el casting
    	$casting = CastingPeer::buscar ( $ci->getCasting() );
    	
    	// 2 - Busco la agencia
    	$agencia = AgenciaPeer::buscar( $ci->getAgencia() );

    	// 3 - Busco la persona base por dni
    	$personas = PersonaPeer::buscarPorDni( $ci->getDni() ); 
    	
    	// 4 - Obentgo la fecha de nacimiento
    	$fechaNacimiento = GlobalFunctions::parsearFecha($ci->getFechaNacimiento() ); 
    	
    	$persona = null;
    	
    	if ( $personas == null || count ( $personas ) == 0 )
    	{
    		 // busco por nombre y fecha
    		
    		 $personas = PersonaPeer::buscarPersonasPorNombreyAnioNacimiento( $ci->getNombre() , $fechaNacimiento);
    		 if ( $personas != null && count ( $personas ) > 0 )
    		 {
    		 	$persona = $personas[0];
    		 }	 	
    	}
    	else 
    	{
    		$persona = $personas[0];
    	}
    	
    	$f_new = false;
    	if ( $persona == null )
    	{
    		//Creo la persona
    		$persona = new Persona();
			$persona->setNombre (trim(strtoupper($ci->getNombre())));
			$persona->setPeso ( $ci->getPeso() );
			$persona->setAltura ( $ci->getAltura() );	
			$persona->setFechaNacimiento($fechaNacimiento);
			$persona->setDni($ci->getDni() );
			$persona->setObservaciones ( $ci->getObservaciones() );
			$persona->setCalzado( $ci->getCalzado() );  
    		$persona->setCamisa( $ci->getCamisa() );  
    		$persona->setPantalon( $ci->getPantalon() );  
			
			// TODO!!!!
			$persona->setTelefono($ci->getTelefono());
			$persona->setCelular ($ci->getCelular() );
			$persona->setEmail($this->getEmail());
			
			$persona->save();
			
			$f_new = true;
    	}
    	
    	$personaCasting = new PersonaCasting();
    	$personaCasting->setAltura( $ci->getAltura() );
    	$personaCasting->setPeso ( $ci->getPeso() );
    	$personaCasting->setCalzado( $ci->getCalzado() );  
    	$personaCasting->setCamisa( $ci->getCamisa() );  
    	$personaCasting->setPantalon( $ci->getPantalon() );  
    	$personaCasting->setObservaciones( $ci->getObservaciones() );
    	
    	// TODO
    	
    	$personaCasting->setTelefono($ci->getTelefono());
	$personaCasting->setCelular ($ci->getCelular() );
	$personaCasting->setEmail($this->getEmail());

    	$personaCasting->setPersona( $persona );
    	$personaCasting->setCasting( $casting );
    	
    	// TODO
    	$personaCasting->setAgencia ( $agencia ); 
    	
    	$personaCasting->save();
    	
    	MediaPeer::doMediaCast($personaCasting, $ci , $f_new);
	}
	
} // CastImport
