<?php


/**
 * Skeleton subclass for performing query and update operations on the 'codigos_scouting' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 01/22/11 21:25:06
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CodigosScoutingPeer extends BaseCodigosScoutingPeer {

	public static function buscar ( $descripcion )
	{
		$codigo = null;
		
		if ( $descripcion == "" )
		{
			$codigo = self::retrieveByPK(-1);
		}
		else 
		{
			$c = new Criteria();
			
			$c->add ( self::DESCRIPCION , $descripcion , Criteria::EQUAL );
			
			$codigos = self::doSelect ( $c );
			
			if ( count($codigos) == 0 )
			{
				$codigo = new CodigosScouting();
				$codigo->setDescripcion( $descripcion);
				$codigo->save();
			}
			else 
			{
				$codigo = $codigos[0];
			}
		}
		return $codigo;
	}
	
} // CodigosScoutingPeer
