<?php



/**
 * Skeleton subclass for performing query and update operations on the 'nacionalidad' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Sun Feb 27 19:31:11 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class NacionalidadQuery extends BaseNacionalidadQuery {

} // NacionalidadQuery
