<?php


/**
 * Skeleton subclass for performing query and update operations on the 'nacionalidad' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 01/22/11 21:25:09
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class NacionalidadPeer extends BaseNacionalidadPeer {
	
	public static function buscar ( $descripcion )
	{
		$nacionalidad = null;
		
		if ( $descripcion == "" )
		{
			$nacionalidad = self::retrieveByPK(-1);
		}
		else
		{
			$c = new Criteria();
			
			$c->add ( self::DESCRIPCION , $descripcion , Criteria::EQUAL );
			
			$nacionalidades = self::doSelect($c);
			
			if ( count($nacionalidades) == 0 )
			{
				$nacionalidad = new Nacionalidad();
				$nacionalidad->setDescripcion( $descripcion );
				$nacionalidad->save(); 
			}
			else
			{
				$nacionalidad = $nacionalidades[0];
			}
		}
		
		return $nacionalidad;
	}
	
} // NacionalidadPeer
